// This file is regenerated by `ts-rs` from Rust derives. Manual edits are
// overwritten on the next `cargo test --test rust export_bindings` (or
// `cargo test --test rust_types`). See C5 in the deepening plan.

export type PaymentSplit = { mode: string; amount: number };
export type SaleItem = {
  id: number; kind: string; item_id: number | null; formula_id: number | null;
  display_name: string; sku_code: string | null; qty: number; price: number;
  unit_type: string; line_discount: number; shade_note: string | null;
  line_order: number; returned_qty: number;
};
export type Sale = {
  id: number; no: string; customer_id: number | null; customer_name: string | null;
  date: string; status: string; subtotal: number; bill_discount: number;
  total: number; paid_amount: number; payment_modes: PaymentSplit[];
  validity_days: number | null; converted_from_id: number | null;
  user_id: number; created_at: string; items: SaleItem[];
};
export type Item = {
  id: number; sku_code: string; barcode: string | null; name: string;
  brand: string | null; category: string | null; unit_code: string;
  unit_label: string; unit: string; units_per_pack: number | null;
  sell_unit: string; sell_unit_id: number | null; retail_price_paise: number;
  cost_paise: number; promo_price_paise: number | null; label_line1: string | null;
  label_line2: string | null; primary_location_id: number | null;
  sub_location_id: number | null; position: string | null; min_stock: number;
  barcode_format: string | null; is_active: boolean; current_qty: number;
  created_at: string; updated_at: string; brand_id: number | null;
};
export type QtyPerLoc = { location: string; qty: number };
export type ItemLookup =
  | ({ scope: "owner" } & Item)
  | { scope: "cashier"; id: number; sku_code: string; name: string;
      retail_price_paise: number; sell_unit: string; unit: string;
      units_per_pack: number | null; in_stock: number }
  | { scope: "stocker"; id: number; sku_code: string; name: string;
      min_stock: number; qty_per_loc: QtyPerLoc[] };
export type NewItem = {
  name: string; brand?: string | null; brand_id?: number | null; category?: string | null;
  unit?: string | null; unit_code?: string | null; unit_label?: string | null;
  units_per_pack?: number | null; sell_unit?: string | null; sell_unit_id?: number | null;
  retail_price_paise: number; cost_paise: number; promo_price_paise?: number | null;
  label_line1?: string | null; label_line2?: string | null; primary_location_id: number;
  sub_location_id?: number | null; position?: string | null; min_stock?: number | null;
  barcode_format?: string | null; barcode?: string | null;
};
export type ItemFilter = {
  query?: string; brand?: string; category?: string;
  low_stock_only?: boolean; include_inactive?: boolean; archived_only?: boolean;
  limit?: number;
};
export type ItemUpdate = {
  name?: string | null; brand?: string | null; brand_id?: number | null;
  category?: string | null; unit?: string | null; unit_code?: string | null;
  unit_label?: string | null; units_per_pack?: number | null;
  sell_unit?: string | null; sell_unit_id?: number | null;
  retail_price_paise?: number | null; cost_paise?: number | null;
  promo_price_paise?: number | null; label_line1?: string | null;
  label_line2?: string | null; primary_location_id?: number | null;
  sub_location_id?: number | null; position?: string | null;
  min_stock?: number | null; barcode_format?: string | null;
  barcode?: string | null; is_active?: boolean | null;
};
export type Customer = {
  id: number; name: string; phone: string; email: string | null; address: string | null;
  customer_type_id: number | null; type_name: string | null; is_flagged: boolean;
  opening_balance_paise: number; notes: string | null; is_active: boolean;
  created_at: string; updated_at: string; credit_limit: number | null;
};
export type NewCustomer = {
  name: string; phone: string; customer_type_id: number | null;
  is_flagged?: boolean; opening_balance_paise?: number; notes?: string | null;
};
export type CustomerUpdate = {
  name?: string; phone?: string | null; customer_type_id?: number | null;
  is_flagged?: boolean; opening_balance_paise?: number;
  notes?: string | null; is_active?: boolean;
};
export type CustomerBill = {
  sale_id: number; sale_number: string; created_at: string;
  total_paise: number; paid_paise: number; status: string;
};
export type CustomerOutstanding = {
  customer_id: number; opening_balance_paise: number;
  total_sales: number; total_paid: number; total_payments: number;
  outstanding: number;
};
export type CustomerLedgerTransaction = {
  id: number; date: string; kind: "sale" | "payment"; ref_no: string | null;
  description: string | null; debit_paise: number; credit_paise: number;
  balance_paise: number;
};
export type CustomerLedger = {
  customer_id: number; opening_balance_paise: number;
  closing_balance_paise: number; rows: CustomerLedgerTransaction[];
};
export type CreditInvoiceLine = { item_id: number; qty: number; unit_price_paise: number };
export type CreateCustomerCreditInvoiceArgs = {
  customer_id: number; date: string; description: string | null; lines: CreditInvoiceLine[];
};
export type RecordCustomerPaymentArgs = {
  customer_id: number; amount: number; mode: string; date: string; note: string | null;
};
export type Vendor = {
  id: number; name: string; phone: string | null; contact_person: string | null;
  credit_limit: number | null; opening_balance: number; notes: string | null;
  is_active: boolean; created_at: string; updated_at: string;
};
export type NewVendor = {
  name: string; phone?: string | null; contact_person?: string | null;
  credit_limit?: number | null; opening_balance?: number; notes?: string | null;
};
export type VendorUpdate = {
  name?: string; phone?: string | null; contact_person?: string | null;
  credit_limit?: number | null; opening_balance?: number;
  notes?: string | null; is_active?: boolean;
};
export type VendorPayment = {
  vendor_id: number; amount: number; mode: string; date: string; notes?: string | null;
};
export type VendorPaymentRecord = {
  id: number; vendor_id: number; amount: number; mode: string; date: string;
  notes: string | null; user_id: number; created_at: string;
};
export type Brand = { id: number; name: string; prefix: string; next_seq: number };
export type DayClose = {
  id: number; day: string; location_id: number; user_id: number | null;
  opening_cash_paise: number; cash_sales_paise: number; card_sales_paise: number;
  upi_sales_paise: number; expenses_paise: number; cash_in_paise: number;
  cash_out_paise: number; closing_cash_paise: number; actual_cash_paise: number;
  variance_paise: number; note: string | null; created_at: string; updated_at: string;
};
export type DayCloseMode = "shop" | "cashier";
export type DayCloseTotals = {
  user_id: number | null; user_name: string; opening_cash_paise: number;
  cash_sales_paise: number; card_sales_paise: number; upi_sales_paise: number;
  cash_in_paise: number; cash_out_paise: number; closing_cash_paise: number;
  actual_cash_paise: number; variance_paise: number;
};
export type DayClosePreview = {
  mode: DayCloseMode; day: string; location_id: number;
  shop_total: DayCloseTotals; per_cashier: DayCloseTotals[];
};
