//! Auth slice (Slice A) — orchestrator.
//!
//! Re-exports the public surface of the submodules so callers
//! (`ipc_auth`, `pde`, `pin_entry`, `recovery`, `sales`, etc.) keep using
//! `crate::commands::auth::*` paths unchanged. Submodule map:
//!
//! - [`types`]: User / Session / AppState / BoundedSettings / Bootstrap / `now_unix`
//! - [`keystore`]: encrypted SQLite sidecar (`KeystoreConn`, `open_keystore`,
//!   keywrap / lockout row I/O, blob encrypt/decrypt)
//! - [`lockout`]: PIN format, lockout backoff, deception flag, wipe-on-lockout
//!   (incl. backup-before-wipe) and `unlock_into_decoy`
//! - [`session`]: `current_session`, `current_user`, `verify_owner_pin`
//! - [`commands`]: every `#[tauri::command]` the frontend calls

mod commands;
mod keystore;
mod lockout;
mod session;
mod types;

// --- Types ---
pub use types::{
    AppState, Bootstrap, BoundedSettings, BoundedSettingsGuard, Session, UnlockResult, User,
};

// --- Keystore (public API) ---
pub use keystore::{decrypt_keystore_blob, default_lockout_row, encrypt_keystore_blob};

// --- Keystore (crate-internal) ---
#[allow(unused_imports)]
pub(crate) use keystore::{
    clear_lockout_keystore, keystore_path, open_keystore, read_keywrap_from_keystore,
    read_lockout_from_keystore, write_keywrap_to_keystore, write_lockout_to_keystore,
};

// --- Time helper ---
pub(crate) use types::now_unix;

// --- Lockout / deception (public API) ---
pub use lockout::validate_owner_pin;

// --- Tauri commands (frontend entry points) ---
// `__cmd__*` and `__tauri_command_name_*` are generated by the
// `#[tauri::command]` macro in `commands.rs`. Tauri's `generate_handler!`
// resolves them at the same path as the command function, so we
// re-export them here to keep `commands::auth::app_bootstrap` invokable
// from `lib.rs`'s `invoke_handler!`.
pub use commands::{
    __cmd__app_bootstrap,
    __cmd__change_pin,
    __cmd__create_user,
    __cmd__delete_user,
    __cmd__list_users,
    __cmd__lock,
    __cmd__login_user,
    __cmd__logout_for_switch,
    __cmd__touch_activity,
    __cmd__unlock,
    __cmd__wipe_and_reset,
    __tauri_command_name_app_bootstrap,
    __tauri_command_name_change_pin,
    __tauri_command_name_create_user,
    __tauri_command_name_delete_user,
    __tauri_command_name_list_users,
    __tauri_command_name_lock,
    __tauri_command_name_login_user,
    __tauri_command_name_logout_for_switch,
    __tauri_command_name_touch_activity,
    __tauri_command_name_unlock,
    __tauri_command_name_wipe_and_reset,
    app_bootstrap,
    change_pin,
    create_user,
    delete_user,
    list_users,
    lock,
    login_user,
    logout_for_switch,
    touch_activity,
    unlock,
    wipe_and_reset,
};

// `current_session` is defined in `session.rs` (it wraps `build_session`).
pub use session::{
    __cmd__current_session, __tauri_command_name_current_session, current_session,
};

// --- Public free functions used by middleware / cross-slice callers ---
pub use session::{current_user, verify_owner_pin};
